{
"month" : 2,
"year" : 2013,
"events": [
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/summer-2013-opportunities-in-turkey-and-the-uk",  
  "id" : "summer-2013-opportunities-in-turkey-and-the-uk",  
  "month" : 2,  
  "year" : 2013,
  "day" : 1,
  "startTime" : "11:18",  
  "endTime" : "11:18", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "am",  
  "am_pm_start" : "am", 
  "am_pm_end" : "am", 
  "title" : "Summer 2013 International Internships in Turkey and the UK",  
  "location" :  "",  
  "details" : "If you are interested in interning abroad this summer and would like a new experience that will not cost too much, please consider applying to go to Turkey through the LSA International Internship Program.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Summer 2013 International Internships in Turkey and the UK"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/deadline-cgis-2013-summer-fall-academic-year-study-abroad",  
  "id" : "deadline-cgis-2013-summer-fall-academic-year-study-abroad",  
  "month" : 2,  
  "year" : 2013,
  "day" : 1,
  "startTime" : "8:51",  
  "endTime" : "8:51", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Deadline: CGIS 2013 Summer/Fall/Academic Year Study Abroad",  
  "location" :  "",  
  "details" : "Center for Global and Intercultural Studies applications for Summer/Fall/Academic Year 2013 study abroad are due on February 1st.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Deadline: CGIS 2013 Summer/Fall/Academic Year Study Abroad"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/avery-dennison-company-day",  
  "id" : "avery-dennison-company-day",  
  "month" : 2,  
  "year" : 2013,
  "day" : 4,
  "startTime" : "10:00",  
  "endTime" : "4:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "am", 
  "am_pm_end" : "pm", 
  "title" : "Avery Dennison Company Day",  
  "location" :  "Duderstadt Connector",  
  "details" : "The ECRC is hosting a Company Day for Avery Dennison on February 4 from 10:00 AM to 4:00 PM in the Duderstadt Connector. Stop by to learn more about the Avery Dennison GOLD (Global Operations Leadership Development) Program!",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Avery Dennison Company Day"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/ace-the-interview-1",  
  "id" : "ace-the-interview-1",  
  "month" : 2,  
  "year" : 2013,
  "day" : 4,
  "startTime" : "5:00",  
  "endTime" : "6:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Ace the Interview!",  
  "location" :  "133 Chrysler",  
  "details" : "Learn about several different types of interviews and how to best prepare for each, including behavioral, technical, case, and phone/Skype interviews. ",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Ace the Interview!"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/consumers-energy-company-day",  
  "id" : "consumers-energy-company-day",  
  "month" : 2,  
  "year" : 2013,
  "day" : 5,
  "startTime" : "11:00",  
  "endTime" : "2:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "am", 
  "am_pm_end" : "pm", 
  "title" : "Consumers Energy Company Day",  
  "location" :  "Duderstadt Connector",  
  "details" : "The ECRC is hosting a Company Day for Consumers Energy on February 5 from 11:00 AM to 2:00 PM in the Duderstadt Connector.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Consumers Energy Company Day"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/co-op-lunch-and-learn",  
  "id" : "co-op-lunch-and-learn",  
  "month" : 2,  
  "year" : 2013,
  "day" : 5,
  "startTime" : "12:00",  
  "endTime" : "1:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Co-op Lunch and Learn",  
  "location" :  "133 Chrysler",  
  "details" : "Grab a bite with the ECRC and hear from students about their co-op experiences! You'll learn about the value of doing a co-op versus an internship, as well as get multiple perspectives on co-ops in different industries.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Co-op Lunch and Learn"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/ae-585-seminar-by-dr-yue-yang-of-cornell-university",  
  "id" : "ae-585-seminar-by-dr-yue-yang-of-cornell-university",  
  "month" : 2,  
  "year" : 2013,
  "day" : 5,
  "startTime" : "4:00",  
  "endTime" : "5:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "AE 585 Seminar by Dr Yue Yang of Cornell University",  
  "location" :  "1008 FXB Building, 1320 Beal Avenue, Ann Arbor, MI 48109",  
  "details" : "AE 585 Seminar by Dr Yue Yang of Cornell University",  
  "host" : "Aerospace Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "AE 585 Seminar by Dr Yue Yang of Cornell University"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/raytheon-insider-interview-webinar",  
  "id" : "raytheon-insider-interview-webinar",  
  "month" : 2,  
  "year" : 2013,
  "day" : 5,
  "startTime" : "6:00",  
  "endTime" : "8:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : " Raytheon - Insider Interview Webinar",  
  "location" :  "",  
  "details" : "In this LIVE webinar you will gain in depth knowledge about Raytheon and learn more about how to land a position at this leading global company. You will also have the opportunity to ask questions directly to Raytheon recruiters and employees. We look forward to your participation!",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : " Raytheon - Insider Interview Webinar"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/mock-interviews-conducted-by-general-motors",  
  "id" : "mock-interviews-conducted-by-general-motors",  
  "month" : 2,  
  "year" : 2013,
  "day" : 6,
  "startTime" : "12:51",  
  "endTime" : "12:51", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "am",  
  "am_pm_start" : "am", 
  "am_pm_end" : "am", 
  "title" : "Mock Interviews conducted by General Motors",  
  "location" :  "Duderstadt Study Rooms",  
  "details" : "General Motors will be holding Mock Interviews on February 6, 2013. Students of all majors, degree levels and anticipated graduation dates are eligible to sign-up to participate in these Mock Interviews.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Mock Interviews conducted by General Motors"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/che-seminar-dr-lonnie-shea",  
  "id" : "che-seminar-dr-lonnie-shea",  
  "month" : 2,  
  "year" : 2013,
  "day" : 7,
  "startTime" : "11:30",  
  "endTime" : "12:30", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "am", 
  "am_pm_end" : "pm", 
  "title" : "ChE Seminar - Dr. Lonnie Shea",  
  "location" :  "1017 H.H. Dow",  
  "details" : "Chemical Engineering seminar with Dr. Lonnie Shea of Northwestern University.",  
  "host" : "Chemical Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "ChE Seminar - Dr. Lonnie Shea"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/ae-585-seminar-by-prof-yulia-peet-of-arizona-state",  
  "id" : "ae-585-seminar-by-prof-yulia-peet-of-arizona-state",  
  "month" : 2,  
  "year" : 2013,
  "day" : 7,
  "startTime" : "4:00",  
  "endTime" : "5:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "AE 585 Seminar by Prof Yulia Peet of Arizona State",  
  "location" :  "Boeing Lecture Hall, FXB Building, 1320 Beal Ave",  
  "details" : "AE 585 Seminar by Prof Yulia Peet of Arizona State",  
  "host" : "Aerospace Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "AE 585 Seminar by Prof Yulia Peet of Arizona State"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/fireside-chat-meet-the-ipe-advisors-declare-the-international-minor",  
  "id" : "fireside-chat-meet-the-ipe-advisors-declare-the-international-minor",  
  "month" : 2,  
  "year" : 2013,
  "day" : 7,
  "startTime" : "5:00",  
  "endTime" : "6:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Fireside Chat: Meet the IPE Advisors &amp; Declare the International Minor!",  
  "location" :  "1180 Duderstadt",  
  "details" : "Michigan Engineering empowers students to make a difference in the world: Where will you begin? Get started by attending Fireside Chats sponsored by International Programs in Engineering!",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Fireside Chat: Meet the IPE Advisors &amp; Declare the International Minor!"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/steel-warehouse-office-hours",  
  "id" : "steel-warehouse-office-hours",  
  "month" : 2,  
  "year" : 2013,
  "day" : 8,
  "startTime" : "8:30",  
  "endTime" : "3:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "am", 
  "am_pm_end" : "pm", 
  "title" : "Steel Warehouse Office Hours",  
  "location" :  "Duderstadt Study Room 9",  
  "details" : "Steel Warehouse will hold office hours on a drop-in basis on Friday, February 8 from 8:30 AM-3:00 PM in Duderstadt Center Study Room #9.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Steel Warehouse Office Hours"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/information-technology-and-actuarial-career-opportunity-day",  
  "id" : "information-technology-and-actuarial-career-opportunity-day",  
  "month" : 2,  
  "year" : 2013,
  "day" : 8,
  "startTime" : "10:30",  
  "endTime" : "3:30", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "am", 
  "am_pm_end" : "pm", 
  "title" : "Information Technology and Actuarial  Career Opportunity Day",  
  "location" :  "6101 Anacapri Blvd., Lansing, MI 48917",  
  "details" : "Auto-Owners Insurance invites all Juniors, Seniors and recent grads majoring in Computer Science, Information Systems, Actuarial Science, Math and Computer Engineering to a free lunch at our home office.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Information Technology and Actuarial  Career Opportunity Day"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/2013-james-r-mellor-lecture",  
  "id" : "2013-james-r-mellor-lecture",  
  "month" : 2,  
  "year" : 2013,
  "day" : 8,
  "startTime" : "11:30",  
  "endTime" : "12:30", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "am", 
  "am_pm_end" : "pm", 
  "title" : "2013 James R. Mellor Lecture",  
  "location" :  "Chesebrough Auditorium ",  
  "details" : "The impact of engineers on society: Differentiating practical from merely possible",  
  "host" : "Michigan Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "2013 James R. Mellor Lecture"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/nyc-turing-fellowship",  
  "id" : "nyc-turing-fellowship",  
  "month" : 2,  
  "year" : 2013,
  "day" : 8,
  "startTime" : "4:30",  
  "endTime" : "4:30", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "NYC Turing Fellowship",  
  "location" :  "",  
  "details" : "University of Michigan students are invited to apply to the third annual NYC Turing Fellowship, a program that matches outstanding computer science and engineering students (undergraduates and graduates) with paid summer internships at leading NYC startups.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "NYC Turing Fellowship"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/deadline-aiesec-summer-2013-teach-english-in-china",  
  "id" : "deadline-aiesec-summer-2013-teach-english-in-china",  
  "month" : 2,  
  "year" : 2013,
  "day" : 8,
  "startTime" : "11:59",  
  "endTime" : "11:59", 
  "hideTime":"false",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Deadline: AIESEC Summer 2013 Teach English in China",  
  "location" :  "",  
  "details" : "The deadline to apply to AIESEC teaching program is February 8th at 11:59 PM.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Deadline: AIESEC Summer 2013 Teach English in China"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/chinese-new-year-tet",  
  "id" : "chinese-new-year-tet",  
  "month" : 2,  
  "year" : 2013,
  "day" : 10,
  "startTime" : "1:18",  
  "endTime" : "1:18", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Chinese New Year &amp; Tet ",  
  "location" :  "",  
  "details" : "Chinese New Year &amp; Tet ",  
  "host" : "Michigan Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Chinese New Year &amp; Tet "} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/alumni-association-linkedin-event",  
  "id" : "alumni-association-linkedin-event",  
  "month" : 2,  
  "year" : 2013,
  "day" : 11,
  "startTime" : "10:49",  
  "endTime" : "10:49", 
  "hideTime":"true",  
  "deadline":"false",
  "am_pm" : "am",  
  "am_pm_start" : "am", 
  "am_pm_end" : "am", 
  "title" : "Alumni Association LinkedIn Event",  
  "location" :  "",  
  "details" : "The Alumni Association is thrilled to welcome John Hill, Higher Education Evangelist at LinkedIn to the University of Michigan on Monday, February 11th for three special engagements \u2013- one for you, one for students, and one for alumni (in Ann Arbor or LiveStream). A networking reception will take place between the student and alumni event. All events are complimentary, but registration is requested.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Alumni Association LinkedIn Event"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/united-airlines-info-session-hosted-by-triangle-fraternity",  
  "id" : "united-airlines-info-session-hosted-by-triangle-fraternity",  
  "month" : 2,  
  "year" : 2013,
  "day" : 11,
  "startTime" : "3:00",  
  "endTime" : "5:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "United Airlines Info Session hosted by Triangle Fraternity",  
  "location" :  "Duderstadt Connector and 1017 DOW",  
  "details" : "Triangle Fraternity will be hosting United Airlines, the world's largest airline, for a r\u00e9sum\u00e9 critiquing session followed by a corporate information session",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "United Airlines Info Session hosted by Triangle Fraternity"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/aisin-technical-center-of-america-company-day",  
  "id" : "aisin-technical-center-of-america-company-day",  
  "month" : 2,  
  "year" : 2013,
  "day" : 12,
  "startTime" : "11:00",  
  "endTime" : "3:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "am", 
  "am_pm_end" : "pm", 
  "title" : "Aisin Technical Center of America Company Day",  
  "location" :  "Duderstadt Connector",  
  "details" : "The ECRC is hosting a Company Day for Aisin Technical Center of America on February 12 from 11:00 AM to 3:00 PM in the Duderstadt Connector.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Aisin Technical Center of America Company Day"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/fall-2013-spring-2014-and-virtual-internships-with-the-u-s-department-of-state",  
  "id" : "fall-2013-spring-2014-and-virtual-internships-with-the-u-s-department-of-state",  
  "month" : 2,  
  "year" : 2013,
  "day" : 12,
  "startTime" : "6:00",  
  "endTime" : "7:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Fall 2013, Spring 2014, and Virtual Internships with the U.S. Department of State",  
  "location" :  "Frey Foundation Classroom, 1210 Weill Hall",  
  "details" : "Interested in combining coursework with an internship or part-time virtual internship in Washington DC or at a U.S. embassy overseas during the Fall 2013 or Spring 2014 semester?  If so, be sure to attend this session with Diplomat in Residence Jim Ellickson-Brown, who will review the application process for the U.S. Department of State Student Internship Program.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Fall 2013, Spring 2014, and Virtual Internships with the U.S. Department of State"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/ash-wednesday",  
  "id" : "ash-wednesday",  
  "month" : 2,  
  "year" : 2013,
  "day" : 13,
  "startTime" : "1:26",  
  "endTime" : "1:26", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Ash Wednesday",  
  "location" :  "",  
  "details" : "Ash Wednesday",  
  "host" : "Michigan Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Ash Wednesday"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/ace-the-interview",  
  "id" : "ace-the-interview",  
  "month" : 2,  
  "year" : 2013,
  "day" : 13,
  "startTime" : "4:30",  
  "endTime" : "5:30", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Ace the Interview",  
  "location" :  "133 Chrysler",  
  "details" : "Attend this workshop to learn how to ace the interview! Please RSVP through ENGenius.Jobs if you plan to attend.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Ace the Interview"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/bosch-information-session",  
  "id" : "bosch-information-session",  
  "month" : 2,  
  "year" : 2013,
  "day" : 13,
  "startTime" : "5:30",  
  "endTime" : "7:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Bosch Information Session",  
  "location" :  "Chesebrough Auditorium",  
  "details" : "Come learn about working for a global company on technologies for future cars, industrial machines, solar energy, wind energy, other forms of energy conversion and storage, and much more. Please RSVP if you would like to attend.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Bosch Information Session"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/earth2019s-changing-climate-with-dr-henry-pollack",  
  "id" : "earth2019s-changing-climate-with-dr-henry-pollack",  
  "month" : 2,  
  "year" : 2013,
  "day" : 14,
  "startTime" : "3:30",  
  "endTime" : "4:30", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Earth\u2019s Changing Climate with Dr. Henry Pollack",  
  "location" :  "Space Research Building Auditorium, Room 2246",  
  "details" : "The Arctic region is experiencing climate change at a pace far faster than the rest of the globe, due to climatological factors that cause what is known as polar amplification. Learn about these changes with Professor Emeritus Henry Pollack.",  
  "host" : "Atmospheric, Oceanic and Space Sciences", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Earth\u2019s Changing Climate with Dr. Henry Pollack"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/invited-seminar-anion-responsive-imidazolium-based-polymers-and-advanced-materials",  
  "id" : "invited-seminar-anion-responsive-imidazolium-based-polymers-and-advanced-materials",  
  "month" : 2,  
  "year" : 2013,
  "day" : 14,
  "startTime" : "4:00",  
  "endTime" : "5:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Invited Seminar: Anion Responsive Imidazolium-Based Polymers and Advanced Materials",  
  "location" :  "1010 HH Dow",  
  "details" : "Invited Seminar: Anion Responsive Imidazolium-Based Polymers and Advanced Materials",  
  "host" : "Michigan Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Invited Seminar: Anion Responsive Imidazolium-Based Polymers and Advanced Materials"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/ae-585-seminar-by-prof-matthew-peet-of-arizona-state-university",  
  "id" : "ae-585-seminar-by-prof-matthew-peet-of-arizona-state-university",  
  "month" : 2,  
  "year" : 2013,
  "day" : 14,
  "startTime" : "4:00",  
  "endTime" : "5:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "AE 585 Seminar by Prof Matthew Peet of Arizona State University",  
  "location" :  "Boeing Lecture Hall, FXB Building, 1320 Beal Ave",  
  "details" : "AE 585 Seminar by Prof Matthew Peet of Arizona State University",  
  "host" : "Aerospace Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "AE 585 Seminar by Prof Matthew Peet of Arizona State University"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/donald-l-katz-lectureship-in-chemical-engineering-dr-michael-doherty-first-lecture",  
  "id" : "donald-l-katz-lectureship-in-chemical-engineering-dr-michael-doherty-first-lecture",  
  "month" : 2,  
  "year" : 2013,
  "day" : 14,
  "startTime" : "5:00",  
  "endTime" : "6:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Donald L. Katz Lectureship in Chemical Engineering - Dr. Michael Doherty, First Lecture",  
  "location" :  "Gerald R. Ford Library Auditorium",  
  "details" : "Dr. Michael Doherty of the University of California at Santa Barbara delivers his first of two Donald L. Katz lectures in Chemical Engineering.",  
  "host" : "Chemical Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Donald L. Katz Lectureship in Chemical Engineering - Dr. Michael Doherty, First Lecture"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/fireside-chat-fall-in-love-with-study-abroad-in-china",  
  "id" : "fireside-chat-fall-in-love-with-study-abroad-in-china",  
  "month" : 2,  
  "year" : 2013,
  "day" : 14,
  "startTime" : "5:00",  
  "endTime" : "6:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Fireside Chat: Fall in Love with Study Abroad in China",  
  "location" :  "Chrysler Lobby",  
  "details" : "Hear more about IPE's programs in China and our partnership with Shanghai Jiao Tong University Joint Institute.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Fireside Chat: Fall in Love with Study Abroad in China"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/donald-l-katz-lectureship-in-chemical-engineering-dr-michael-doherty-second-lecture",  
  "id" : "donald-l-katz-lectureship-in-chemical-engineering-dr-michael-doherty-second-lecture",  
  "month" : 2,  
  "year" : 2013,
  "day" : 15,
  "startTime" : "10:00",  
  "endTime" : "11:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "am",  
  "am_pm_start" : "am", 
  "am_pm_end" : "am", 
  "title" : "Donald L. Katz Lectureship in Chemical Engineering - Dr. Michael Doherty, Second Lecture",  
  "location" :  "Gerald R. Ford Library Auditorium",  
  "details" : "Dr. Michael Doherty of the University of California at Santa Barbara delivers his second Donald L. Katz lectures in Chemical Engineering.",  
  "host" : "Chemical Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Donald L. Katz Lectureship in Chemical Engineering - Dr. Michael Doherty, Second Lecture"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/deadline-international-institute-individual-fellowships",  
  "id" : "deadline-international-institute-individual-fellowships",  
  "month" : 2,  
  "year" : 2013,
  "day" : 15,
  "startTime" : "11:59",  
  "endTime" : "11:59", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "am",  
  "am_pm_start" : "am", 
  "am_pm_end" : "am", 
  "title" : "Deadline: International Institute Individual Fellowships",  
  "location" :  "",  
  "details" : "The International Institute Individual Fellowships are designed to support University of Michigan students, regardless of citizenship, who are enrolled in a degree program and wish to participate in internships or conduct research abroad. Award amounts are up to $5,000.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Deadline: International Institute Individual Fellowships"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/deadline-summer-2013-international-research-opportunites-in-india",  
  "id" : "deadline-summer-2013-international-research-opportunites-in-india",  
  "month" : 2,  
  "year" : 2013,
  "day" : 15,
  "startTime" : "1:40",  
  "endTime" : "1:40", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Deadline: Summer 2013 International Research Opportunites in India",  
  "location" :  "",  
  "details" : "We are working in placements for small groups of students from U-M and the other partner schools in the CIC and Georgetown to go to India and conduct research in biotechnology, global health, and engineering. Students should be able to have airfare and housing covered and receive a stipend. U-M students should apply to Sandra Gregerman, who will forward applications. Students with research experience will be more competitive.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Deadline: Summer 2013 International Research Opportunites in India"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/event-study-business-in-italy-this-may",  
  "id" : "event-study-business-in-italy-this-may",  
  "month" : 2,  
  "year" : 2013,
  "day" : 15,
  "startTime" : "2:00",  
  "endTime" : "3:30", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Event: Study Business in Italy this May",  
  "location" :  "International Center Room 9 (603 E. Madison St.)",  
  "details" : "Take a course or two in Italy this spring. THe internatioal Summer PRgogram in Management (ISPM-Italy) allows you to study in beautiful Padova, Italy. Learn more; come to an informational meeting on Friday February 15th, at 2pm in the International Center Room 9 (603 E. Madison Street).",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Event: Study Business in Italy this May"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/info-session-aiesec-work-abroad",  
  "id" : "info-session-aiesec-work-abroad",  
  "month" : 2,  
  "year" : 2013,
  "day" : 16,
  "startTime" : "7:00",  
  "endTime" : "8:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Info Session: AIESEC Work Abroad",  
  "location" :  "3460 Mason Hall",  
  "details" : "AIESEC is the world's largest student organization, located in over 110 countries. Our mission is to foster leadership development and create change agents who have a positive impact on their societies. Attend this info session for more information.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Info Session: AIESEC Work Abroad"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/how-to-job-search-smarter-the-trouble-with-job-boards",  
  "id" : "how-to-job-search-smarter-the-trouble-with-job-boards",  
  "month" : 2,  
  "year" : 2013,
  "day" : 19,
  "startTime" : "12:00",  
  "endTime" : "1:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "How to Job Search Smarter: The Trouble With Job Boards ",  
  "location" :  "",  
  "details" : "Join us monthly at noon EST for 45-minutes and call-in for your career to receive highly focused, content-rich live teleseminars designed to meet the needs of busy professionals. Your Career Call-In is free for Alumni Association members; registration is required.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "How to Job Search Smarter: The Trouble With Job Boards "} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/ae-585-seminar-by-dr-hemanth-kolla-of-sandia-national-laboratories",  
  "id" : "ae-585-seminar-by-dr-hemanth-kolla-of-sandia-national-laboratories",  
  "month" : 2,  
  "year" : 2013,
  "day" : 19,
  "startTime" : "4:00",  
  "endTime" : "5:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "AE 585 Seminar by Dr. Hemanth Kolla of Sandia National Laboratories",  
  "location" :  "",  
  "details" : "AE 585 Seminar by Dr. Hemanth Kolla of Sandia National Laboratories",  
  "host" : "Aerospace Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "AE 585 Seminar by Dr. Hemanth Kolla of Sandia National Laboratories"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/last-day-to-withdraw-from-winter-2013-term-with-tuition-reduction",  
  "id" : "last-day-to-withdraw-from-winter-2013-term-with-tuition-reduction",  
  "month" : 2,  
  "year" : 2013,
  "day" : 19,
  "startTime" : "4:02",  
  "endTime" : "4:02", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Last day to withdraw from Winter 2013 term with tuition reduction.",  
  "location" :  "",  
  "details" : "Last day to withdraw from Winter 2013 term with fifty percent tuition reduction.",  
  "host" : "Michigan Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Last day to withdraw from Winter 2013 term with tuition reduction."} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/coe-junior-dinner",  
  "id" : "coe-junior-dinner",  
  "month" : 2,  
  "year" : 2013,
  "day" : 19,
  "startTime" : "6:00",  
  "endTime" : "8:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Michigan Engineering Junior Dinner",  
  "location" :  "Tishman Hall, Bob &amp; Betty Beyster Bldg",  
  "details" : "The Junior Dinner promotes graduate education with assistance from our graduate chairs, faculty and current graduate students. Participation in the event is by invitation only.",  
  "host" : "Graduate Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Michigan Engineering Junior Dinner"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/deadline-2013-summer-study-abroad-applications-final-deadline",  
  "id" : "deadline-2013-summer-study-abroad-applications-final-deadline",  
  "month" : 2,  
  "year" : 2013,
  "day" : 20,
  "startTime" : "3:04",  
  "endTime" : "3:04", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Deadline: 2013 Summer Study Abroad Applications (Final Deadline)",  
  "location" :  "",  
  "details" : "Priority deadline for the following programs is February 6, 2013. Applications completed by this date will be reviewed for early admission.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Deadline: 2013 Summer Study Abroad Applications (Final Deadline)"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/ae-585-seminar-by-dr-ashwin-dani-of-the-university-of-illinois",  
  "id" : "ae-585-seminar-by-dr-ashwin-dani-of-the-university-of-illinois",  
  "month" : 2,  
  "year" : 2013,
  "day" : 21,
  "startTime" : "4:00",  
  "endTime" : "5:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "AE 585 Seminar by Dr Ashwin Dani of the University of Illinois",  
  "location" :  "",  
  "details" : "AE 585 Seminar by Dr Ashwin Dani of the University of Illinois",  
  "host" : "Aerospace Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "AE 585 Seminar by Dr Ashwin Dani of the University of Illinois"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/fireside-chat-financial-aid-and-study-abroad",  
  "id" : "fireside-chat-financial-aid-and-study-abroad",  
  "month" : 2,  
  "year" : 2013,
  "day" : 21,
  "startTime" : "5:00",  
  "endTime" : "6:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Fireside Chat: Financial Aid and Study Abroad",  
  "location" :  "Chrysler Center Lobby",  
  "details" : "Identify ways to help fund your international experiences.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Fireside Chat: Financial Aid and Study Abroad"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/leadership-skills-for-new-supervisors",  
  "id" : "leadership-skills-for-new-supervisors",  
  "month" : 2,  
  "year" : 2013,
  "day" : 22,
  "startTime" : "9:00",  
  "endTime" : "12:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "am", 
  "am_pm_end" : "pm", 
  "title" : "Leadership Skills for New Supervisors",  
  "location" :  "Johnson Rooms",  
  "details" : "This course is designed to provide strategies, skills, and tools of leadership that will make the transition to being a supervisor smoother and more successful.  ",  
  "host" : "Human Resources", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Leadership Skills for New Supervisors"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/deadline-raoul-wallenberg-international-summer-travel-fellowship",  
  "id" : "deadline-raoul-wallenberg-international-summer-travel-fellowship",  
  "month" : 2,  
  "year" : 2013,
  "day" : 22,
  "startTime" : "2:14",  
  "endTime" : "2:14", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Deadline: Raoul Wallenberg International Summer Travel Fellowship",  
  "location" :  "",  
  "details" : "In the spirit of Raoul Wallenberg\u2019s experience at Michigan, the Raoul Wallenberg International Summer Travel Fellowship will allow selected students to take part in a community service project or civic participation any where in the world.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Deadline: Raoul Wallenberg International Summer Travel Fellowship"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/3rd-annual-student-symposium-on-global-service-engagement",  
  "id" : "3rd-annual-student-symposium-on-global-service-engagement",  
  "month" : 2,  
  "year" : 2013,
  "day" : 23,
  "startTime" : "2:00",  
  "endTime" : "4:30", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "3rd Annual Student Symposium on Global Service Engagement",  
  "location" :  "Pendleton Room, Michigan Union",  
  "details" : "",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "3rd Annual Student Symposium on Global Service Engagement"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/indonesian-cultural-night",  
  "id" : "indonesian-cultural-night",  
  "month" : 2,  
  "year" : 2013,
  "day" : 23,
  "startTime" : "5:30",  
  "endTime" : "5:30", 
  "hideTime":"false",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Indonesian Cultural Night",  
  "location" :  "Angell Hall Auditorium B",  
  "details" : "PERMIAS Michigan (Indonesian Student Association) hosts the Indonesian Cultural Night, the organization's biggest event of the year.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Indonesian Cultural Night"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/deadline-funding-for-research-or-internship-support-in-africa-african-studies-center",  
  "id" : "deadline-funding-for-research-or-internship-support-in-africa-african-studies-center",  
  "month" : 2,  
  "year" : 2013,
  "day" : 24,
  "startTime" : "2:28",  
  "endTime" : "2:28", 
  "hideTime":"true",  
  "deadline":"true",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Deadline: Funding for Research or Internship Support in Africa - African Studies Center",  
  "location" :  "",  
  "details" : "ASC seeks applications from University of Michigan students for a limited number of grants toward summer or semester-long research projects or internships at institutions and businesses in Africa.",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Deadline: Funding for Research or Internship Support in Africa - African Studies Center"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/cse-distinguished-lecture-hal-abelson",  
  "id" : "cse-distinguished-lecture-hal-abelson",  
  "month" : 2,  
  "year" : 2013,
  "day" : 25,
  "startTime" : "4:30",  
  "endTime" : "5:30", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "CSE Distinguished Lecture: Hal Abelson",  
  "location" :  "1670 Beyster Building",  
  "details" : "In this talk Abelson will describe some things done at MIT and elsewhere to support computational values, like open publication of all our course materials, faculty policies on open publication of academic research, and plans for open online instruction based on non-proprietary software platforms",  
  "host" : "Electrical Engineering and Computer Science", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "CSE Distinguished Lecture: Hal Abelson"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/ae-585-seminar-by-dr-karthik-duraisamy-of-stanford-university",  
  "id" : "ae-585-seminar-by-dr-karthik-duraisamy-of-stanford-university",  
  "month" : 2,  
  "year" : 2013,
  "day" : 26,
  "startTime" : "4:00",  
  "endTime" : "5:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Multi-fidelity Modeling of Aerodynamics and Acoustics in Complex Rotating Blade Applications",  
  "location" :  "1008 FXB Building, 1320 Beal Avenue, Ann Arbor, MI 48109",  
  "details" : "AE 585 Seminar by Dr Karthik Duraisamy of Stanford University.",  
  "host" : "Aerospace Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Multi-fidelity Modeling of Aerodynamics and Acoustics in Complex Rotating Blade Applications"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/bender-virtual-career-fair-employment-for-people-with-disabilities",  
  "id" : "bender-virtual-career-fair-employment-for-people-with-disabilities",  
  "month" : 2,  
  "year" : 2013,
  "day" : 27,
  "startTime" : "9:00",  
  "endTime" : "4:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "am", 
  "am_pm_end" : "pm", 
  "title" : "Bender Virtual Career Fair - Employment for People with Disabilities",  
  "location" :  "",  
  "details" : "Are you a person with a disability looking for a career opportunity or internship? This Virtual Career Fair is FREE for students and alumni with disabilities to attend. Students and alumni are invited to interact with employers via chat sessions.",  
  "host" : "Engineering Career Resource Center", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Bender Virtual Career Fair - Employment for People with Disabilities"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/ae-585-seminar-by-prof-derek-paley-of-the-university-of-maryland",  
  "id" : "ae-585-seminar-by-prof-derek-paley-of-the-university-of-maryland",  
  "month" : 2,  
  "year" : 2013,
  "day" : 28,
  "startTime" : "4:00",  
  "endTime" : "5:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "AE 585 Seminar by Prof Derek Paley of the University of Maryland",  
  "location" :  "Boeing Lecture Hall, FXB Building, 1320 Beal Avenue",  
  "details" : "Derek Paley Associate Professor  of the University of Maryland gives UM Aerospace Seminar on Feb 28, 2012",  
  "host" : "Aerospace Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "AE 585 Seminar by Prof Derek Paley of the University of Maryland"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/invited-seminar-self-healing-biomaterials",  
  "id" : "invited-seminar-self-healing-biomaterials",  
  "month" : 2,  
  "year" : 2013,
  "day" : 28,
  "startTime" : "4:00",  
  "endTime" : "5:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Invited Seminar: Self-Healing Biomaterials",  
  "location" :  "1010 HH Dow",  
  "details" : "Invited Seminar: Self-Healing Biomaterials.",  
  "host" : "Michigan Engineering", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Invited Seminar: Self-Healing Biomaterials"} 

},
{
  "url" : "http://www.engin.umich.edu/college/about/cal/events/2013/february/fireside-chat-bienvenido-region-focus-the-spanish-speaking-world",  
  "id" : "fireside-chat-bienvenido-region-focus-the-spanish-speaking-world",  
  "month" : 2,  
  "year" : 2013,
  "day" : 28,
  "startTime" : "5:00",  
  "endTime" : "6:00", 
  "hideTime":"false",  
  "deadline":"false",
  "am_pm" : "pm",  
  "am_pm_start" : "pm", 
  "am_pm_end" : "pm", 
  "title" : "Fireside Chat: \u00a1Bienvenido!",  
  "location" :  "Chrysler Lobby",  
  "details" : "This Week's Topic: Region Focus - The Spanish-Speaking World. Discover engineering opportunities abroad in Spanish-speaking countries. Free food!",  
  "host" : "International Programs", 
  "image" : {"src" : "http://www.engin.umich.edu/++resource++umich_images/default_event.jpg", "alt" : "Fireside Chat: \u00a1Bienvenido!"} 

}
]
}